### ISSUE TITLE
Import Python examples

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-api-docs-site#4]
https://github.com/turtlecoin/turtlecoin-walletd-rpc-python

**Comment by ar-x** [comment]
http://turtlecoin-python.readthedocs.io/en/latest/api/wallet.html

**Comment by ar-x** [comment]
Adding this for more context to others:

https://hinata-104.shadow-clone-jutsu.com/

The idea is to add usage examples for https://github.com/turtlecoin/turtlecoin-walletd-rpc-python to the right side bar.

This specific on is for the Python RPC client to the TurtleCoin Walletd service. The service is described here: https://wiki.bytecoin.org/wiki/Bytecoin_RPC_Wallet_JSON_RPC_API.

The first thing to do would be to download turtlecoin from https://turtlecoin.lol/, and get to a point where you can use walletd. See: https://github.com/turtlecoin/turtlecoin-wiki/wiki/Bootstrapping-the-Blockchain.

**Comment by timmcleod** [comment]
Ok @ar-x, so I'm not a python guy, but the python wrapper doesn't appear to allow access to the raw response or the underlying JSON. 

So, if we want to include the python wrapper in the docs, we'll need to do something differently with the sections that show the "Expected output", since the python wrapper doesn't allow a way to output the JSON as far as I can tell.

One option could be to change the wording from "Expected output:" to something else... like "Expected RPC response:" or something along those lines, and in the python examples, show what the methods return in a different way. Maybe just a line at the bottom of the example that is commented out, showing the method's result. Open to ideas here.

Another option could be to see if @arthurk would be interested in modifying his wrapper to work like the others and just return the response itself, or the body of the response.

Let me know your thoughts.

**Comment by arthurk** [comment]
Hey, currently only part of the json response is returned ("result") and the other two keys ("id" and "jsonrpc") are omitted. I'm open to modifying it, the change is trivial and I'll do it in the next days.

Good job with the docs site! I didn't know about this project, looks really cool

**Comment by timmcleod** [comment]
Nice @arthurk, that would be awesome. Thanks! Maybe tag a new version since it would be a breaking change in case anyone is using it. Is the python wallet using it? Let me know when it’s done and I’ll put some examples together for the docs. I may get your input on them if you don’t mind, just to make sure they’re pythony..

**Comment by ar-x** [comment]
@arthurk It would be awesome to get the Python examples sorted out for the api docs site.

**Comment by arthurk** [comment]
Done! Released new version that includes raw json response

**Comment by ar-x** [comment]
@arthurk Super! Thanks.

**Comment by ar-x** [comment]
@arthurk Do you want to take a shot at importing the Python examples. It all goes here: https://raw.githubusercontent.com/ar-x/turtlecoin-wiki/import-api-docs/api/wallet-rpc-api.md (and i can help). Otherwise one of us will eventually get to t.

**Comment by arthurk** [comment]
I have a lot of things to do right now and can't spend much time on it but I can review it if someone creates the examples

**Comment by ar-x** [comment]
I've put up a 80K bounty for this.

**Comment by ar-x** [comment]
Closing this in favor of https://github.com/turtlecoin/turtlecoin-docs/issues/157
